package com.pmarek.memoryGame.Graphics;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.pmarek.memoryGame.Card.Card;
import com.pmarek.memoryGame.utils.GameResult;
import com.pmarek.memoryGame.utils.InputManager;
import com.pmarek.memoryGame.utils.DatabaseConnection;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Set;

public class Leaderboards extends JFrame {
    private JButton playAgainButton;
    private JTable table;
    private JPanel mainPanel;
    private JScrollPane scrollPane;

    private ArrayList<GameResult> gameResults;

    public Leaderboards() {
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setContentPane(mainPanel);

        playAgainButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                int cardPairNumber = InputManager.getCardPairNumber();
                Set<Card> cardSet = Card.initializeCardSet(cardPairNumber);
                GameWindow gameWindow = new GameWindow("Memory", cardSet);
            }
        });
        DatabaseConnection connection = new DatabaseConnection();
        connection.createNewTable();
        gameResults = connection.selectAllResults();
        createUIComponents();

        this.setVisible(true);
        this.pack();
    }

    private void createUIComponents() {
        String[] columnNames = {"Nickname",
                "Score"};
        Object[][] data = null;
        if (gameResults != null) {
            data = gameResults.stream().map(gameResult -> gameResult.toArray()).toArray(Object[][]::new);
        }
        table = new JTable(data, columnNames);

        scrollPane.setViewportView(table);
        table.setEnabled(false);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        playAgainButton = new JButton();
        playAgainButton.setText("Play again");
        panel1.add(playAgainButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scrollPane = new JScrollPane();
        panel1.add(scrollPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        table = new JTable();
        scrollPane.setViewportView(table);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
